corrected CI v.7

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -6,19 +6,19 @@ on:
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
-    services:
-      postgres:  # Required for Testcontainers and database tests
-        image: postgres:latest
-        env:
-          POSTGRES_USER: test
-          POSTGRES_PASSWORD: test
-          POSTGRES_DB: test
-        ports:
-          - 5432:5432
-        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
-      docker:
-        image: docker:dind
-        options: --privileged
+    #services:
+      #postgres:  # Required for Testcontainers and database tests
+        #image: postgres:latest
+        #env:
+          #POSTGRES_USER: test
+          #POSTGRES_PASSWORD: test
+          #POSTGRES_DB: test
+        #ports:
+          #- 5432:5432
+        #options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+     #docker:
+        #image: docker:dind
+        #options: --privileged
 
     steps:
       # 1. Clone the repository
@@ -48,8 +48,8 @@ jobs:
         run: docker info
 
       # 5. Wait for PostgreSQL to initialize
-      - name: Wait for PostgreSQL
-        run: sleep 10
+      #- name: Wait for PostgreSQL
+        #run: sleep 10
 
       # 6.1. Maven downloads common-events from GitHub Packages to Actions
       - name: Set up Maven settings.xml for GitHub Packages
@@ -74,12 +74,12 @@ jobs:
       - name: Build and test with Maven (Testcontainers)
         env:
           SPRING_PROFILES_ACTIVE: test
-          TESTCONTAINERS_RYUK_DISABLED: "true"      # Disable Ryuk for better stability
+          #TESTCONTAINERS_RYUK_DISABLED: "true"      # Disable Ryuk for better stability
           MAVEN_OPTS: "-Dmaven.repo.local=.m2"      # Use local Maven cache
         run: |
-          mvn -B clean install -e -X -Dspring.test.constructor.autowire.mode=all
-          pkill -f surefirebooter || true           # Kill any stuck test processes
+          mvn -B clean verify -e -X -Dspring.test.constructor.autowire.mode=all
 
+      #pkill -f surefirebooter || true           # Kill any stuck test processes
       # 7. Upload test reports if tests fail
       - name: Upload Surefire Reports
         if: failure()
